# Generated by Django 6.0.4 on 2026-04-18 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('crop_type', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('current_stage', models.CharField(choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('READY', 'Ready'), ('HARVESTED', 'Harvested')], default='PLANTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'FIELD_AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stage', models.CharField(choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('READY', 'Ready'), ('HARVESTED', 'Harvested')], max_length=20)),
                ('new_stage', models.CharField(choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('READY', 'Ready'), ('HARVESTED', 'Harvested')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='fields.field')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['assigned_agent'], name='idx_field_agent'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['current_stage'], name='idx_field_stage'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['planting_date'], name='idx_field_planting_date'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['assigned_agent', 'current_stage'], name='idx_field_agent_stage'),
        ),
        migrations.AddIndex(
            model_name='fieldupdate',
            index=models.Index(fields=['field', '-created_at'], name='idx_update_field_date'),
        ),
        migrations.AddIndex(
            model_name='fieldupdate',
            index=models.Index(fields=['-created_at'], name='idx_update_created_at'),
        ),
    ]
