# Generated by Django 5.0.4 on 2026-04-20 18:44

from django.db import migrations
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.hashers import make_password


def seed_initial_data(apps, schema_editor):
    """Create initial admin user, field agent, and sample fields"""

    # Get the historical versions of models
    User = apps.get_model('accounts', 'User')
    Field = apps.get_model('fields', 'Field')

    # Create admin user
    admin_username = 'admin'
    admin_email = 'admin@smartseason.com'
    admin_password = 'Admin123!'

    if not User.objects.filter(username=admin_username).exists():
        User.objects.create(
            username=admin_username,
            email=admin_email,
            password=make_password(admin_password),  # Use make_password instead
            role='ADMIN',
            is_superuser=True,
            is_staff=True,
            is_active=True,
        )
        print(f"✅ Created admin user: {admin_username}")
    else:
        print(f"⚠️ Admin user '{admin_username}' already exists")

    # Create field agent
    agent_username = 'fieldagent'
    agent_email = 'agent@smartseason.com'
    agent_password = 'Agent123!'

    agent, created = User.objects.get_or_create(
        username=agent_username,
        defaults={
            'email': agent_email,
            'password': make_password(agent_password),  # Use make_password
            'role': 'FIELD_AGENT',
            'is_active': True,
        }
    )

    if created:
        print(f"✅ Created field agent: {agent_username}")
    else:
        print(f"⚠️ Field agent '{agent_username}' already exists")
        # Ensure agent has correct role
        if agent.role != 'FIELD_AGENT':
            agent.role = 'FIELD_AGENT'
            agent.save()

    # Create sample fields only if agent exists
    if agent:
        today = timezone.now().date()
        sample_fields = [
            {
                'name': 'North Field - Maize',
                'crop_type': 'Maize',
                'planting_date': today - timedelta(days=30),
                'current_stage': 'GROWING',
            },
            {
                'name': 'South Field - Wheat',
                'crop_type': 'Wheat',
                'planting_date': today - timedelta(days=90),
                'current_stage': 'READY',
            },
            {
                'name': 'East Field - Rice',
                'crop_type': 'Rice',
                'planting_date': today - timedelta(days=10),
                'current_stage': 'PLANTED',
            },
            {
                'name': 'West Field - Corn',
                'crop_type': 'Corn',
                'planting_date': today - timedelta(days=120),
                'current_stage': 'HARVESTED',
            },
        ]

        for field_data in sample_fields:
            field, field_created = Field.objects.get_or_create(
                name=field_data['name'],
                defaults={
                    'crop_type': field_data['crop_type'],
                    'planting_date': field_data['planting_date'],
                    'current_stage': field_data['current_stage'],
                    'assigned_agent': agent,
                }
            )
            if field_created:
                print(f"✅ Created field: {field.name}")
            else:
                print(f"⚠️ Field already exists: {field.name}")


def remove_seed_data(apps, schema_editor):
    """Remove seeded data (for reverse migration)"""
    User = apps.get_model('accounts', 'User')
    Field = apps.get_model('fields', 'Field')

    # Delete fields first (due to foreign key)
    Field.objects.filter(name__icontains='North Field').delete()
    Field.objects.filter(name__icontains='South Field').delete()
    Field.objects.filter(name__icontains='East Field').delete()
    Field.objects.filter(name__icontains='West Field').delete()

    # Delete users
    User.objects.filter(username='fieldagent').delete()
    User.objects.filter(username='admin').delete()

    print("✅ Removed seeded data")


class Migration(migrations.Migration):
    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_initial_data, remove_seed_data),
    ]